services:
  crafty-service:
    build:
      context: ./crafty-service
      dockerfile: Dockerfile
      args:
        SKIP_SUBMODULES: "true"
    environment:
      APP_ENV: ${APP_ENV}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DATABASE_URL: mysql+pymysql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}
      COOLIFY_URL: https://crafty.why-ai.net:4000
      COOLIFY_FQDN: crafty.why-ai.net:4000
      LOG_LEVEL: debug
    ports:
      - "4000:4000"
    depends_on:
      - db
    entrypoint: ["wait-for-it", "db:${DB_PORT}", "--", "poetry", "run", "crafty"]
    networks:
      - crafty_network
    logging:
      driver: "json-file"  # The default log driver
      options:
        max-size: "10m"  # Maximum log file size before it is rotated
        max-file: "3"    # Number of log files to keep

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - crafty_network
    volumes:
      - db_data:/var/lib/mysql

  crafty-ui:
    build:
      context: ./crafty-ui
      dockerfile: Dockerfile
      args:
        SKIP_SUBMODULES: "true"
    ports:
      - "80:80"
    networks:
      - crafty_network
    environment:
      - LOG_LEVEL=debug  # Set your desired log level
    logging:
      driver: "json-file"  # The default log driver
      options:
        max-size: "10m"  # Maximum log file size before it is rotated
        max-file: "3"    # Number of log files to keep

networks:
  crafty_network:
    driver: bridge

volumes:
  db_data:
