name: Crafty Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repo (Deployment Repository)
      uses: actions/checkout@v2
      with:
        submodules: false  # Skip submodule initialization for the main repo

    - name: Checkout frontend repo (master branch)
      run: |
        git clone --depth 1 https://github.com/TerroqDev/crafty-ui.git crafty-ui  # Manually clone without submodules
      continue-on-error: true  # This prevents failure if the repo doesn't exist

    - name: Checkout backend repo (master branch)
      run: |
        git clone --depth 1 https://github.com/TerroqDev/crafty-service.git crafty-service  # Manually clone without submodules
      continue-on-error: true  # This prevents failure if the repo doesn't exist

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Create external traefik network if not exists
      run: |
        docker network create traefik || true

    - name: Build and run Docker containers
      run: |
        docker-compose -f docker-compose.yaml up --build -d
